# Generated by Django 5.2.3 on 2025-08-10 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homi', '0004_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('shared_payment', 'Pago de Gasto Compartido')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_expenses', to='homi.household')),
                ('shared_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_expense', to='homi.expensepayment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'household', 'month', 'year'], name='homi_person_user_id_e4e280_idx')],
            },
        ),
    ]
